Have made many clients through the server
java-park-mail-ru/Something2.5D-09-2017 pull request #19
Opened 2017-11-29 22:19 UTC by ZubAnt

2017-12-01 14:04 UTC, isopov commented
1. UserServiceTest - сделайте его транзакционным (одну строчку добавить), уберите из него создание настоящего веб-сервера (RANDOM_PORT поменять на NONE). По желанию - уберите случайность -  важные качества тестов это повторяемость и воспроизводимость.
2. UserControllerTest - тут не так просто - реальный веб-сервер тут реально используется, при этом тесты ходят в реальную базу - этот тест не может быть транзакционным - в идеале его хорошо бы переделать, замокав UserService.
3. Тесты на систему сообщений - то что вам класс Message сериализуется и десериализуется в правильные тестовые json-строки.
4. Тесты на механику - что-нибудь из подключения к игре, движения, получения информации о движении другими игроками (без реального веб-сервера в тестах - на моках)
5. Странное у вас какое-то использвание Hibernate-а - чисто для обновления схемы БД, а запросы к ней через jdbcTemplate - вам это показалось удобным?

2017-12-01 14:05 UTC, isopov requested changes
В общих тестах к PR.

2017-12-02 23:43 UTC, ZubAnt commented
1. Сделали UserServiceTest транзакционным
3. Добавили тесты на сериализацию TankSnap и ServerSnap
4. Добавили следующие тесты к игровой механике:
- Тесты на контроль количества отправляемых снэпшотов танка. Их количество должно быть равным количеству клиентов, успевших отослать свои координаты хотя бы одни раз за время *sleep*-a *MechanicsExecutor*-а
- Тесты на контроль корректности отправляемого снэпшота сервера. Всем игрокам отправляется список всех обрабатываемых снэпшотов танка. В случае одного подключенного клиента, он получаем информацию только о себе. В случае нескольких клиентов, клиент получает информацию ещё и о враге. В случае отсутствия клиентов отправка сообщения производиться не будет
5. Просто так сложилось. И нам показалось это удобным
6. Мы отсылаем всем клиентам все танки, даже себя самого. Обработку переложили на клиентскую сторону

2017-12-06 08:43 UTC, isopov commented
CoordinateFactory, ServerSnapFactory, TankSnapFactory, UserFactory - такое ощущение, что вы пытаетесь издеваться над тупыми java-программистами, которые не могут просто объект создать, а им обязательно для этого фабрика нужна. Получается плохо - такое только в анекдотах бывает, или вот в вашем коде. Если залезть в код спринга или бута, то всякие AbstractServletWebServerFactory существуют не для "энтерпрайзного вида", а по конкретным причинам....

2017-12-06 09:40 UTC, merged