Developer
java-park-mail-ru/Something2.5D-09-2017 pull request #7
Opened 2017-09-20 09:14 UTC by ZubAnt

2017-09-20 09:47 UTC, KSolovyev requested changes

2017-09-20 09:47 UTC, KSolovyev commented on src/test/java/com/tp/tanks/TanksApplicationTests.java
> +//package com.tp.tanks;
закомментированного кода не должно быть. Удалите, пожалуйста

2017-09-20 09:47 UTC, KSolovyev commented on src/main/java/com/tp/tanks/model/User.java
> +public class User {
Вы используете разметку JPA, но всю работу выполняете через JDBC. Предлагаю разметку убрать. Лучше, конечно, вообще отложить работу с базой на следующий модуль, потому что сейчас возникнет много проблем

2017-09-20 09:47 UTC, KSolovyev commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
вот это будет вам сбрасывать базу пользователей после каждого рестарта. Так делать не стоит

2017-09-20 09:47 UTC, KSolovyev commented on src/main/java/com/tp/tanks/service/UserService.java
> +
пожалуйста, уберите пустые строки после try и после catch

2017-09-20 09:47 UTC, KSolovyev commented on src/main/java/com/tp/tanks/service/UserService.java
> +                System.out.println("password not equal");
писать наружу надо с помощью логгера
https://technopark-mail.slack.com/archives/C206Q4UKZ/p1505762334000232

2017-09-20 09:47 UTC, KSolovyev commented on pom.xml
> +		<!--<dependency>-->
закомментированный код

2017-09-20 16:42 UTC, KSolovyev requested changes

2017-09-20 16:42 UTC, KSolovyev commented on src/main/java/com/tp/tanks/controller/SingUpController.java
> +@SuppressWarnings("SpringAutowiredFieldsWarningInspection")
не надо так. Сделайте лучше как он просит в инспекции

2017-09-20 16:42 UTC, KSolovyev commented on src/main/java/com/tp/tanks/service/UserService.java
> +@SuppressWarnings("SpringAutowiredFieldsWarningInspection")
и здесь тоже

2017-09-20 16:42 UTC, KSolovyev commented on src/main/java/com/tp/tanks/controller/SingUpController.java
> +        session.setAttribute("user", loginUser);
мне не очень нравится идея класть в сессию потенциально изменяемый объект. Давайте лучше положим в сессию userId

2017-09-20 20:17 UTC, ZubAnt commented on src/main/java/com/tp/tanks/service/UserService.java
> +@SuppressWarnings("SpringAutowiredFieldsWarningInspection")
Пофиксили. BCryptPasswordEncoder стреляет. Из-за него почему-то циклическая зависимость получается и все падает успешно. Решили времено с использованием аннотации @Lazy. Это верное решение?

2017-09-21 09:57 UTC, KSolovyev requested changes
поправьте конфиг и давайте будем мержить

2017-09-21 09:57 UTC, KSolovyev commented on src/main/resources/application.properties
> +spring.jpa.show-sql=true
это дебажная опция, надо убрать

2017-09-21 09:57 UTC, KSolovyev commented on src/main/resources/application.properties
> +spring.mvc.view.prefix=/WEB-INF/views/
это вам точно не надо

2017-09-21 09:57 UTC, KSolovyev commented on src/main/resources/application.properties
> +spring.mvc.view.suffix= .jsp
это тоже стоит убрать

2017-09-21 09:57 UTC, KSolovyev commented on src/main/resources/application.properties
> +spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
я сегодня спрошу, что это значит =)

2017-09-21 11:21 UTC, KSolovyev approved these changes

2017-09-21 11:24 UTC, merged